import PDFDocument from 'pdfkit';

export function generateTranscriptPDF(podcast, options = {}, stream) {
  const {
    includeTranscript = true,
    includeShortSummary = false,
    includeDetailedSummary = false,
    includeKeyPoints = false,
    includeTopics = false,
  } = options;

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        autoFirstPage: true
      });

      if (stream) {
        doc.pipe(stream);
      }

      doc.on('end', () => {
        console.log('✅ PDF Generation Complete');
        resolve();
      });

      doc.on('error', (err) => {
        console.error('❌ PDF Generation Error:', err);
        reject(err);
      });

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text(podcast.title, { align: 'center' });
    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#666666')
      .text(`Generated by PodAccess • ${new Date(podcast.uploadDate).toLocaleDateString()}`, {
        align: 'center',
      });
    doc.moveDown(2);

    // Detailed Summary
    if (includeDetailedSummary && podcast.detailedSummary) {
      doc.fillColor('#000000').fontSize(16).font('Helvetica-Bold').text('Detailed Summary');
      doc.moveDown(0.5);
      const summaryText = Array.isArray(podcast.detailedSummary) ? podcast.detailedSummary.join('\n\n') : podcast.detailedSummary;
      doc.fontSize(11).font('Helvetica').text(summaryText, { align: 'justify', lineGap: 3 });
      doc.moveDown(1.5);
    }

    // Short Summary
    if (includeShortSummary && podcast.shortSummary) {
      doc.fillColor('#000000').fontSize(16).font('Helvetica-Bold').text('Short Summary');
      doc.moveDown(0.5);
      const shortText = Array.isArray(podcast.shortSummary) ? podcast.shortSummary.join('\n\n') : podcast.shortSummary;
      doc.fontSize(11).font('Helvetica').text(shortText, { align: 'justify', lineGap: 3 });
      doc.moveDown(1.5);
    }

    // Key Points
    if (includeKeyPoints && podcast.keyPoints?.length > 0) {
      doc.fillColor('#000000').fontSize(16).font('Helvetica-Bold').text('Key Highlights');
      doc.moveDown(0.5);
      podcast.keyPoints.forEach(point => {
        doc.fontSize(11).font('Helvetica').text(`• ${point}`, { indent: 20, lineGap: 2 });
      });
      doc.moveDown(1.5);
    }

    // Topics/Keywords
    if (includeTopics && podcast.keywords?.length > 0) {
      doc.fillColor('#000000').fontSize(16).font('Helvetica-Bold').text('Main Topics');
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica').text(podcast.keywords.join(' • '), { lineGap: 2 });
      doc.moveDown(1.5);
    }

    // Transcript
    if (includeTranscript) {
      doc.fillColor('#000000').fontSize(16).font('Helvetica-Bold').text('Full Transcript');
      doc.moveDown(1);
      doc.fontSize(11);

      if (podcast.segments?.length > 0) {
        let currentSpeaker = null;
        for (const segment of podcast.segments) {
          if (segment.speaker !== currentSpeaker) {
            currentSpeaker = segment.speaker;
            doc.moveDown(0.5).font('Helvetica-Bold').text(`${currentSpeaker}:`);
            doc.font('Helvetica');
          }
          doc.text(segment.text, { align: 'left', lineGap: 4 });
        }
      } else {
        doc.font('Helvetica').text(podcast.transcript, { align: 'left', lineGap: 4 });
      }
    }

    doc.end();
    } catch (err) {
      console.error('❌ PDF Generator Exception:', err);
      reject(err);
    }
  });
}
