import { jsPDF } from 'jspdf';

export function downloadTranscriptPDF(podcast) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 50;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addText = (text, options = {}) => {
    const { fontSize = 11, fontStyle = 'normal', color = [30, 30, 30] } = options;
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', fontStyle);
    doc.setTextColor(...color);

    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += fontSize * 1.4;
    }
  };

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(13, 148, 136);
  const titleLines = doc.splitTextToSize(podcast.title, maxWidth);
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += 26;
  }

  y += 10;
  addText(`Generated by PodAccess • ${new Date(podcast.uploadDate).toLocaleDateString()}`, {
    fontSize: 9,
    color: [100, 100, 100],
  });

  y += 20;

  if (podcast.segments?.length > 0) {
    let currentSpeaker = null;
    for (const segment of podcast.segments) {
      if (segment.speaker !== currentSpeaker) {
        currentSpeaker = segment.speaker;
        y += 8;
        addText(`${currentSpeaker}:`, { fontStyle: 'bold', fontSize: 12, color: [15, 118, 110] });
      }
      addText(segment.text);
    }
  } else {
    addText(podcast.transcript);
  }

  const safeTitle = podcast.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`${safeTitle}_transcript.pdf`);
}
